### ISSUE TITLE
Get back the sites that are indexed to a comID

### ISSUE THREAD

**Issue by jkreft-usgs** [internetofwater/nldi-services#14]
right now there is basically a bare json response here:
 http://cida.usgs.gov/nldi/comid/23382345/

it would be valuable to be able to see the sites that are linked to that comID.

**Comment by kkehl-usgs** [comment]
Does "linked" mean we should upstream to find the next upstream site, and look downstream to find the next downstream site -- and then show those like next and previous?  Or does "linked" mean something else?

**Comment by dblodgett-usgs** [comment]
It just means those that are indexed to that COMID locally.

I could see doing a new path like:
`https://labs.waterdata.usgs.gov/api/nldi/linked-data/comid/23382345/linked-features` that would give back a geoJSON representation of all the features linked to that comid that would use the same schema as the result of navigation. e.g. `https://labs.waterdata.usgs.gov/api/nldi/linked-data/comid/23382345/navigate/DM/nwissite` but from all sources and only sites that are linked to the local catchment .

**Comment by kkehl-usgs** [comment]
https://labs.waterdata.usgs.gov/api/nldi/linked-data/comid/23382345/linked-features or https://labs.waterdata.usgs.gov/api/nldi/linked-data/nwissite/0123456789/linked-features would behave the same way

**Comment by jkreft-usgs** [comment]
I think we should punt on this for the moment.  There is not an immediate use case.

**Comment by dblodgett-usgs** [comment]
I don't disagree. It does seem like a generally useful feature to discover other nearby features, but it's not critical. @kkehl-usgs have you gotten into it yet? If you have, and it's not going to be much more work, maybe we finish it, but otherwise, let's set this aside.

**Comment by kkehl-usgs** [comment]
I started looking at it a bit yesterday.  It looks like 2-3 days work.  I'll hold off, then.

**Comment by dblodgett-usgs** [comment]
I want to put this in the context of a rudimentary html client for a given feature. Will work up a summary issue for that work and link it to this.

**Comment by dblodgett-usgs** [comment]
superseded by #20
