### ISSUE TITLE
Consider addressing duplication of APIs between LinkedDataController and NetworkController

### ISSUE THREAD

**Issue by kkehl-usgs** [internetofwater/nldi-services#163]
The NetworkController duplicates the functionality of LinkedDataController in the getFeatures() and getFlowlines() APIs.   The difference is that the NetworkController knows the comid so can avoid the cost of one database query, whereas the LinkedDataController has to look it up.

One way to address this in a version 2 of the APIs would be for LinkedDataController to accept an optional comid parameter.  This means the corresponding NetworkController APIs could be eliminated.

**Comment by EthanGrahn** [comment]
@dblodgett-usgs I think we can close this out. With the content negotiation update, we factored out the comid endpoints into their own functions to be able to handle the response objects separately. https://github.com/internetofwater/nldi-services/blob/master/src/main/java/gov/usgs/owi/nldi/controllers/NetworkController.java
