### ISSUE TITLE
Swagger default values?

### ISSUE THREAD

**Issue by dblodgett-usgs** [internetofwater/nldi-services#184]
Is there an annotation for swagger documentation in Spring Boot to set defaults for the Swagger documentation? 

Not really sure what to google for to find out -- maybe @kkehl-usgs can just point me in the right direction?

**Comment by kkehl-usgs** [comment]
@RequestParam(value=Parameters.DISTANCE, required=false, defaultValue=Parameters.MAX_DISTANCE)

Adding defaults or changing them can potentially break unit tests, fyi.

**Comment by EthanGrahn** [comment]
@dblodgett-usgs I found a `@Schema` option that is purely for swagger values and puts a default value into the UI.
