### ISSUE TITLE
Multiple IDs for getCharacteristicData

### ISSUE THREAD

**Issue by cheginit** [internetofwater/nldi-services#237]
I am wondering if it is possible to change `getCharacteristicData` so it can accept multiple feature IDs rather than making several requests, one ID at a time. There could be a limit, for example 10 IDs or something like that.

**Comment by dblodgett-usgs** [comment]
Good idea -- We'll look at what the limit ought to be. I would expect we can go fairly high. The question will be, what's the right way to specify the input list? The Water Quality Portal handles it by allowing an NLDI navigation request that implies the list to be passed in. An ad-hoc list is also possible, but a little more complicated and less scalable. Thoughts?

**Comment by cheginit** [comment]
If by specifying the input list, you mean from user to NLDI service, I just looked at USGS's REST documentation and found this:

> You can use either site or sites for the URL argument name. sites corresponds to one or more site numbers. Separate sites with commas. There is no limit to the number of sites you can specify, however there may be limitations imposed by the HTTP GET protocol, your client application and the USGS application server. The site number may be optionally prefixed by the agency code followed by a colon, which ensures the site is unique.

Many services that I have used are similar to this. Some services that support POST as well as GET, add a manual limit. For example, `MaxRecordCount` for [NHDPlus HR](https://hydro.nationalmap.gov/arcgis/rest/services/NHDPlus_HR/MapServer/2) is 1000.

**Comment by dblodgett-usgs** [comment]
This has been overcome by events and will need to be rethought. I think it may make the most sense to create a pygeoapi process for characteristics that uses HyRiver. For the python rewrite of the NLDI, I think we should probably deprecate the characteristics end point.
