### ISSUE TITLE
Create a CONTRIBUTING.md document

### ISSUE THREAD

**Issue by EthanGrahn** [internetofwater/nldi-services#276]
We should create a document outlining the workflow to contribute. This link can provide a good format to start with. https://mozillascience.github.io/working-open-workshop/contributing/

**Comment by ksonda** [comment]
Feel free to crib from this (slides 43-50) https://lincolninst-my.sharepoint.com/:p:/g/personal/konda_lincolninst_edu/EVthmPM-2S9NuDOeOktw6vUBPmO5X0OiaDYyaxgwQer8NA?e=UoUuRM

**Comment by EthanGrahn** [comment]
Thanks Kyle! That brings up a new issue. We have 2 different types of contributors to the NLDI projects.
1. data contributors
2. code contributors

We need to take that into account and have sections that outline both.
