### ISSUE TITLE
PLANNING: JSON-LD media type

### ISSUE THREAD

**Issue by dblodgett-usgs** [internetofwater/nldi-services#280]
This wiki: https://github.com/internetofwater/nldi-services/wiki/NLDI-schema.org-JSON-LD-media-type is all set up. 

I'd like to scope out an update to the NLDI network attributes using https://www.sciencebase.gov/catalog/item/60c92503d34e86b9389df1c9 and a JSON-LD media type. The major other addition will be exposing the mainstem URI as a component of the nldi content. 

I will plan on working with @EthanGrahn and @ksonda on this over the next few weeks for implementation in June.

**Comment by EthanGrahn** [comment]
Considering discussions in #298 and #299 should we close out this planning issue?
