### ISSUE TITLE
Output individual NLDI feature as json-ld representation.

### ISSUE THREAD

**Issue by dblodgett-usgs** [internetofwater/nldi-services#298]
Based on the outcome of #280 allow f=jsonld or the appropriate content type header to trigger the jsonld media type response. This would include the mainstem the feature is on and the `@id` of the feature is to be the existing `url` attribute of the feature.

**Comment by dblodgett-usgs** [comment]
Chatting with @EthanGrahn and mocked this up. @ksonda any feedback? Ideas?

1. I've used HY_Hydrolocation and schema:Place as types.
2. Source and sourceName are not in the graph - should they be?
3. comid is just an "in" association. Should schema topology be used or geoqparql?
4. we would need some logic to determine what gets put into the indirect position. Features that are tagged as hydrolocation would get a mainstem, features that have reachcode/measure would get the reachcode / measure.
5. we will not include schema:geo for the non--point indexed data that we have just recently implemented support for.

Thoughts?

```json
{
	"@context": [
		{
			"schema": "https://schema.org/",
			"geo": "schema:geo",
			"hyf": "https://www.opengis.net/def/schema/hy_features/hyf/",
			"gsp": "http://www.opengis.net/ont/geosparql#",
			"name": "schema:name",
			"comid": {
				"@id": "schema:containedInPlace",
				"@type": "@id"
			},
			"mainstem": {
				"@id": "schema:url",
				"@type": "@id"
			}
		}
	],
	"@id": "http://www.waterqualitydata.us/provider/NWIS/USGS-WI/USGS-05430050/",
	"@type": [
		"https://www.opengis.net/def/schema/hy_features/hyf/HY_HydroLocation",
		"https://schema.org/Place"
	],
	"source": "WQP",
	"sourceName": "Water Quality Portal",
	"name": "BADFISH CREEK NEAR OREGON, WI",
	"comid": "https://geoconnex.us/nhdplusv2/comid/13296678",
	"hyf:referencedPosition": [
		{
			"hyf:HY_IndirectPosition": {
				"hyf:distanceExpression": {
					"hyf:HY_DistanceFromReferent": {
						"hyf:interpolative": "84.8194"
					}
				},
				"hyf:distanceDescription": {
					"hyf:HY_DistanceDescription": "upstream"
				},
				"hyf:linearElement": "https://labs.waterdata.usgs.gov/geoserver/wmadata/ows?service=WFS&version=1.0.0&request=GetFeature&typeName=wmadata%3Anhdflowline_network&outputFormat=application%2Fjson&cql_filter=reachcode%20=%20%2712040104000071%27"
			}
		},
		{
			"hyf:HY_IndirectPosition": {
				"hyf:linearElement": {
					"@id": "https://geoconnex.us/ref/mainstems/2600464",
					"@type": "hyf:HY_Flowpath"
				}
			}
		}
	],
	"geo": {
		"schema:latitude": 42.9280563,
		"@type": "schema:GeoCoordinates",
		"schema:longitude": -89.329007
	},
	"gsp:hasGeometry": {
		"@type": "http://www.opengis.net/ont/sf#Point",
		"gsp:asWKT": {
			"@value": "POINT(-89.329007 42.9280563)",
			"@type": "http://www.opengis.net/ont/geosparql#wktLiteral"
		}
	}
}
```

**Comment by EthanGrahn** [comment]
We could remove `mainstem` from the context since we'll be putting it in the `hyf:referencedPosition` instead.

**Comment by ksonda** [comment]
for comid, maybe schema:geoWithin if the comid identifier is eventually a semantic resource of type Place, or a catchment area?

Source and sourceName...
elsewhere we use the schema:provider concept, but we haven't thought about it rigorously. Maybe it could be something like

in context, "source": "schema:provider"

and then

"source": {
		"@type": "schema:Organization",
                 "schema:url": "https://waterqualitydata.us",
		"schema:name": "WQP",
                 "schema:description": "Water Quality Portal"
	}

**Comment by ksonda** [comment]
> We could remove `mainstem` from the context since we'll be putting it in the `hyf:referencedPosition` instead.

agree you're not using mainstem as an alias anywhere. I guess if you wanted to you can do this

```
"hyf:HY_IndirectPosition": {
				"mainstem":  "https://geoconnex.us/ref/mainstems/2600464"
				}
			
```
 
and have this in the context

```
"mainstem": {
				"@id": "hyf:linearElement",
				"@type": "@id"
			}
```
and then over in refernce features we type all mainstems as hyf:HY_Flowpath

**Comment by EthanGrahn** [comment]
My understanding of the `mainstem` context that @ksonda suggested is that it makes it slightly simpler to write in the body.
e.g.
```json
"hyf:HY_IndirectPosition": {
   "mainstem": "https://geoconnex.us/ref/mainstems/473915"
 }
```
vs
```json
"hyf:HY_IndirectPosition": {
	"hyf:linearElement": {
		"@id": "https://geoconnex.us/ref/mainstems/2600464",
		"@type": "hyf:HY_Flowpath"
	}
}
```

**Comment by dblodgett-usgs** [comment]
I think just doing it:
```json
"hyf:HY_IndirectPosition": {
   "hyf:linearElement": "https://geoconnex.us/ref/mainstems/473915"
 }
```

Seems fine?

**Comment by ksonda** [comment]
You either need to specify an alias in the context with "@id": "hyf:linearElement" or do 

```
"hyf:HY_IndirectPosition": {
   "hyf:linearElement": {"@id": "https://geoconnex.us/ref/mainstems/473915"}
 }
```

**Comment by ksonda** [comment]
and now that I think about it, reachcode you might want to be

"hyf:linearElement": { "schema:url" (or "@id") : "https://geoconnex.us/nhdplusv2/reachcode/07090002008279"}

**Comment by dblodgett-usgs** [comment]
Ahhh --- we are honing in on two things. I was noting that there is another hyf:linearElement just below mainstem that's linking to the reach geometry. You were keying into the nuance about `@id`. 

@EthanGrahn -- let's use the context to specify that hyf:linearElement is an `@id` and _not_ use the `mainstems` json key in the body of the json-ld.

**Comment by EthanGrahn** [comment]
Not sure that I'm fully grasping what needs to be done. Something like this?
```json
{
  "@context": [
    {
      "schema": "https://schema.org/",
      "geo": "schema:geo",
      "hyf": "https://www.opengis.net/def/schema/hy_features/hyf/",
      "gsp": "http://www.opengis.net/ont/geosparql#",
      "name": "schema:name",
      "comid": {
        "@id": "schema:containedInPlace",
        "@type": "@id"
      },
      "hyf:linearElement": {
        "@type": "@id"
      }
    }
  ],
  "@id": "https://waterdata.usgs.gov/monitoring-location/05430050",
  "@type": [
    "https://www.opengis.net/def/schema/hy_features/hyf/HY_HydroLocation",
    "https://schema.org/Place"
  ],
  "source": "nwissite",
  "sourceName": "NWIS Surface Water Sites",
  "name": "BADFISH CREEK NEAR OREGON, WI",
  "comid": "https://geoconnex.us/nhdplusv2/comid/13296678",
  "hyf:referencedPosition": [
    {
      "hyf:HY_IndirectPosition": {
        "hyf:linearElement": "https://geoconnex.us/ref/mainstems/473915"
      }
    },
    {
      "hyf:HY_IndirectPosition": {
        "hyf:distanceExpression": {
          "hyf:HY_DistanceFromReferent": {
            "hyf:interpolative": "64.4213"
          }
        },
        "hyf:distanceDescription": {
          "hyf:HY_DistanceDescription": "upstream"
        },
        "hyf:linearElement": "https://labs.waterdata.usgs.gov/geoserver/wmadata/ows?service=WFS&version=1.0.0&request=GetFeature&typeName=wmadata%3Anhdflowline_network&outputFormat=application%2Fjson&cql_filter=reachcode='07090002008279'"
      }
    }
  ],
  "geo": {
    "@type": "schema:GeoCoordinates",
    "schema:longitude": -89.329007,
    "schema:latitude": 42.92805628
  },
  "gsp:hasGeometry": {
    "@type": "http://www.opengis.net/ont/sf#Point",
    "gsp:asWKT": {
      "@value": "POINT(-89.329007 42.92805628)",
      "@type": "http://www.opengis.net/ont/geosparql#wktLiteral"
    }
  }
}
```

**Comment by ksonda** [comment]
yeah you're right that works.

@dblodgett-usgs do you want the reachcode to be the geoconnex pid or the wfs call?

Incorporateing everything discussed so far, I think this

```json
 {
 	"@context": [{
 		"schema": "https://schema.org/",
 		"geo": "schema:geo",
 		"hyf": "https://www.opengis.net/def/schema/hy_features/hyf/",
 		"gsp": "http://www.opengis.net/ont/geosparql#",
 		"name": "schema:name",
 		"comid": {
 			"@id": "schema:geoWithin",
 			"@type": "@id"
 		},
 		"hyf:linearElement": {
 			"@type": "@id"
 		},
 		"source": "schema:provider"
 	}],
 	"@id": "https://waterdata.usgs.gov/monitoring-location/05430050",
 	"@type": [
 		"https://www.opengis.net/def/schema/hy_features/hyf/HY_HydroLocation",
 		"https://schema.org/Place"
 	],
 	"source": {
 		"@type": "schema:Organization",
 		"schema:url": "https://waterqualitydata.us",
 		"schema:name": "WQP",
 		"schema:description": "Water Quality Portal"
 	},
 	"name": "BADFISH CREEK NEAR OREGON, WI",
 	"comid": "https://geoconnex.us/nhdplusv2/comid/13296678",
 	"hyf:referencedPosition": [{
 			"hyf:HY_IndirectPosition": {
 				"hyf:linearElement": "https://geoconnex.us/ref/mainstems/473915"
 			}
 		},
 		{
 			"hyf:HY_IndirectPosition": {
 				"hyf:distanceExpression": {
 					"hyf:HY_DistanceFromReferent": {
 						"hyf:interpolative": "64.4213"
 					}
 				},
 				"hyf:distanceDescription": {
 					"hyf:HY_DistanceDescription": "upstream"
 				},
 				"hyf:linearElement": "https://geoconnex.us/nhdplusv2/reachcode/07090002008279"
 			}
 		}
 	],
 	"geo": {
 		"@type": "schema:GeoCoordinates",
 		"schema:longitude": -89.329007,
 		"schema:latitude": 42.92805628
 	},
 	"gsp:hasGeometry": {
 		"@type": "http://www.opengis.net/ont/sf#Point",
 		"gsp:asWKT": {
 			"@value": "POINT(-89.329007 42.92805628)",
 			"@type": "http://www.opengis.net/ont/geosparql#wktLiteral"
 		}
 	}

 }
```

**Comment by dblodgett-usgs** [comment]
Yeah -- geoconnex pid.

**Comment by ksonda** [comment]
ehh may have to rethink provider as source predicate

https://validator.schema.org/#url=https:%2F%2Freference.geoconnex.us%2Fcollections%2Fdams%2Fitems%2F1000195

**Comment by ksonda** [comment]
some alternative candidates for `schema:provider`

https://schema.org/maintainer
https://schema.org/sourceOrganization


also maybe feature_data_source can be mapped to
https://schema.org/isBasedOn

**Comment by EthanGrahn** [comment]
Out of those two options, I would lean towards maintainer. @dblodgett-usgs what do you think?

**Comment by ksonda** [comment]
I thought about it more, provider could maybe still be sued but the issue is a little deeper. 

https://github.com/internetofwater/tracker/issues/5

**Comment by EthanGrahn** [comment]
One thing to note for the source schema:url is that we don't have info specifically for that. The best I could do is grab the base url from the `@id`. If it uses a subpath, that would make things trickier.

**Comment by dblodgett-usgs** [comment]
Should we drop the `schema:Place` type?  In this case, `@id` is literally a web resource that would be expected to have a `schema:about` that is a `schema:Place`.

**Comment by ksonda** [comment]
dropping schema:Place also fixes the provider/maintainer issue

**Comment by EthanGrahn** [comment]
Mine is generally the same, but includes the `mainstem` alias.

```json
{
  "@context": [
    {
      "schema": "https://schema.org/",
      "geo": "schema:geo",
      "hyf": "https://www.opengis.net/def/schema/hy_features/hyf/",
      "gsp": "http://www.opengis.net/ont/geosparql#",
      "name": "schema:name",
      "source": "schema:provider",
      "comid": {
        "@id": "schema:geoWithin",
        "@type": "@id"
      },
      "mainstem": {
        "@id": "hyf:linearElement",
        "@type": "@id"
      }
    }
  ],
  "@id": "http://www.waterqualitydata.us/provider/NWIS/USGS-WI/USGS-05430050/",
  "@type": "https://www.opengis.net/def/schema/hy_features/hyf/HY_HydroLocation",
  "source": {
    "@type": "schema:Organization",
    "schema:name": "WQP",
    "schema:description": "Water Quality Portal"
  },
  "name": "BADFISH CREEK NEAR OREGON, WI",
  "comid": "https://geoconnex.us/nhdplusv2/comid/13296678",
  "hyf:referencedPosition": [
    {
      "hyf:HY_IndirectPosition": {
        "mainstem": "https://geoconnex.us/ref/mainstems/473915"
      }
    },
    {
      "hyf:HY_IndirectPosition": {
        "hyf:distanceExpression": {
          "hyf:HY_DistanceFromReferent": {
            "hyf:interpolative": "64.4213"
          }
        },
        "hyf:distanceDescription": {
          "hyf:HY_DistanceDescription": "upstream"
        },
        "hyf:linearElement": "https://geoconnex.us/nhdplusv2/reachcode/07090002008279"
      }
    }
  ],
  "geo": {
    "@type": "schema:GeoCoordinates",
    "schema:longitude": -89.329007,
    "schema:latitude": 42.9280563
  },
  "gsp:hasGeometry": {
    "@type": "http://www.opengis.net/ont/sf#Point",
    "gsp:asWKT": {
      "@value": "POINT(-89.329007 42.9280563)",
      "@type": "http://www.opengis.net/ont/geosparql#wktLiteral"
    }
  }
}
```

**Comment by dblodgett-usgs** [comment]
So we still have a minor issue that @ksonda has me thinking about.

```json
{
  "@id": "http://www.waterqualitydata.us/provider/NWIS/USGS-WI/USGS-05430050/",
  "@type": 
  [
    "https://www.opengis.net/def/schema/hy_features/hyf/HY_HydroLocation",
    "https://schema.org/Place"
  ],
  "schema:provider": 
  {
    "@type": "schema:Organization"
  }
}
```

Theoretically works, but many of the things we will have as `@id` in these documents will be identifiers for literal places -- not identifiers for web pages who's subject is a place as is the case here. 

Would it be so bad to look at this as both cases are kind of a hybrid, where the `@id` is kind of always an identifier for the real place and an identifier for a real-world feature? If we do that, then saying that the `@type` is `schema:Place` is correct in both cases -- using indirect identification in one case and direct identification in the other.

**Comment by EthanGrahn** [comment]
I would recommend avoiding ambiguity on whether it might be one thing or another. We can't assume the end user will know which is which.

**Comment by ksonda** [comment]
I tend to agree with @EthanGrahn , although we don't currently have a machine-readable way of disambiguating "real world thing" from "website about that thing" within the NLDI data model other than possibly the use of a geoconnex.us identifier...maybe the NWIS and WQP sites are currently a special case that IMHO could be changed eventually.

That said, @dblodgett-usgs proposal would work if we added "@type": "schema:CreativeWork" to everything, on the wishy-washy premise that the mere act of identifying a location is an act of creation, as is putting a streamgage there or making a website about it.

I prefer replacing the provider concept with subjectOf relationship like this

```json
"schema:subjectOf": {
    "@type": "schema:CreativeWork",
    "schema:identifier": "WQP",
    "schema:name": "Water Quality Portal"
  }
```

or possibly even

```json
"schema:isPartOf": {
    "@type": "schema:Dataset",
    "schema:identifier": "WQP",
    "schema:name": "Water Quality Portal",
    "schema:distribution": {
         "@type": "schema:DataDownload",
         "schema:contentUrl": "https://www.waterqualitydata.us/data/Station/search?mimeType=geojson&minactivities=1&counts=no",
         "schema:contentEncoding": "application/geo+json"
    }
```

**Comment by EthanGrahn** [comment]
I think both options are good. The second is better if we want to be pretty explicit as to what the nldi actually knows about the source. It knows that it retrieved GeoJSON data from that source uri. I'm also partial to not including the contentUrl.

**Comment by ksonda** [comment]
if you don't want to do contentUrl I don't know if I see the value of the second option that much

(1) I'm part of a geojson dataset in a geojson format but you dont need to know the url from here

```json
"schema:isPartOf": {
    "@type": "schema:Dataset",
    "schema:identifier": "WQP",
    "schema:name": "Water Quality Portal",
    "schema:distribution": {
         "@type": "schema:DataDownload",
         "schema:contentEncoding": "application/geo+json"
    }
```

vs

(2)
I'm part of a dataset with this name (and btw by "dataset" in this case i mean federated data system with a common api endpoint but im not giving you any link to it)
```json
"schema:isPartOf": {
    "@type": "schema:Dataset",
    "schema:identifier": "WQP",
    "schema:name": "Water Quality Portal",
```

vs

(3) I am part of something called the WQP
```json
"schema:subjectOf": {
    "@type": "schema:CreativeWork",
    "schema:identifier": "WQP",
    "schema:name": "Water Quality Portal",
```

(3) seems like the least-common denominator and to have the least amount of weird caveats

**Comment by EthanGrahn** [comment]
I agree. `schema:Dataset` doesn't make any sense without pointing to the dataset.

**Comment by dblodgett-usgs** [comment]
Agreed. I guess let's go with 3 and plan on adding a "source information" link to the crawler source table and use it here in the future?
