### ISSUE TITLE
Improve filtering of `getFeatures`

### ISSUE THREAD

**Issue by EthanGrahn** [internetofwater/nldi-services#336]
Currently, requests to `/linked-data/{featureSource}` are not very feasible due to the amount of data that is returned from most sources. Adding filter parameters could make the endpoint more useful.

A use case that I have is that I want to retrieve features from `nwissite` so that I know whether to make subsequent calls rather than attempting calls that will potentially be 404.

Some options would include:
pagination - allows me to get every source, but increases service calls
`?identifier={id1},{id2},...,{idn}` - only returns features in this list of identifiers, limited by url/param length limits

**Comment by dblodgett-usgs** [comment]
A few ideas we've had on this. 
1. return only ids if you did `/linked-data/{featureSource}/ids` as suggested in #20
2. there's been discussion of supporting the `offset={x}&limit={y}` paging pattern as supported by OGC API Features.
3. a `bbox` filter as supported in the core of API features might be a good way to go.
4. there's interest in a multi-ID request pattern in #237 maybe we support a ids={1,2,3,4} pattern where the list of patterns can be a form encoded post if it gets too long?

**Comment by EthanGrahn** [comment]
I think option 1 works best for my use case. Thinking about it again, if I were to makes requests with `?identifier=` for all of the identifiers I have, then I might as well be calling the regular endpoint to see if I get a 404. The time save is not likely to be significant. (still useful for smaller use cases) Option 1 could still run into the same size issue depending on the size of the dataset, although it'll be an improvement over returning all data.

**Comment by EthanGrahn** [comment]
@dblodgett-usgs I think we can close this issue. Adding pagination and other OGC features would resolve this in a more formal way.
