### ISSUE TITLE
Python Rewrite Plan

### ISSUE THREAD

**Issue by dblodgett-usgs** [internetofwater/nldi-services#376]
This issue can be closed when the work for milestone 1 is captured in follow up issues and the other milestones are captured in a github project to track the work.

Milestone 1: Development environment to include small scale and full scale development environments. Artifacts all available on public endpoints. Working with python crawler and java api implementation.

Milestone 2: Design and mock new swagger and crawler source strategy with Python. Include all feature sources in swagger directly. Solves issue of comid vs feature source classes. Simplifies swagger by exposing all available feature sources. 

Milestone 3: Design and prototype SQLAlchemy connector. Enable streaming responses that implement the same logic as the existing NLDI MyBatis implementation.

Milestone 4: Implement Asynchronous Gateway API pattern to integrated new swagger pattern and SQLAlchemy connector. Should lend its self to cloud native scalability. Should integrate work from previous milestones. Should be the first beta release of the new NLDI.

**Comment by dblodgett-usgs** [comment]
Milestones created in https://github.com/internetofwater/nldi-services/milestones

**Comment by dblodgett-usgs** [comment]
I take that back -- milestones are not really supported well through that mechanism. We'll just use custom labels in the project.

**Comment by dblodgett-usgs** [comment]
Notes from kick off meeting here. https://etherpad.wikimedia.org/p/NLDI_Python_Rewrite_Kickoff/timeslider#970

**Comment by brownd-usgs** [comment]
I think we can close this ticket because we have issues created for all four milestones for the rewrite.
